name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo " Creating backup..."
          mkdir -p ~/site-backups
          timestamp=$(date +"%Y-%m-%d-%H%M")
          tar -czf ~/site-backups/backup-$timestamp.tar.gz /var/www/shamsuddin-devops.site
          
          echo "pull code"
          cd /var/www/shamsuddin-devops.site
          git pull origin main

          echo "nginx reload"
          sudo systemctl reload nginx